### ISSUE TITLE
add command line operation for annotation new data

### ISSUE THREAD

**Issue by yardencsGitHub** [yardencsGitHub/tweetynet#12]
We should push towards a command line operation for annotating new data.
Right now it's a short python script .. but there will be a need to import packages etc'.

**Comment by NickleDave** [comment]
The PR that addresses this issue should include a script with the necessary imports and a link to it in the README.md, so that way the example can elide those import requests for the sake of brevity

**Comment by NickleDave** [comment]
Added --predict command-line optioin in 2dd65f77eb5c686d3fe69003903a8d669f1be5e4
