### ISSUE TITLE
add link to pre-train weights + option to fine tune

### ISSUE THREAD

**Issue by NickleDave** [yardencsGitHub/tweetynet#15]
Would be good to train a single model across several birds of a single species then provide a link to pre-trained weights plus a cli option to fine-tune using those weights

**Comment by yardencsGitHub** [comment]
Seems very ambitious. Would be amazing if it worked.
In canaries, different birds can have very different syllables.

**Comment by NickleDave** [comment]
It's a pretty common thing to do. For some reason it works with really disparate training sets, e.g. pre-train on ImageNet and then fine-tune to your comparatively small training set, for whatever your application is, medical image diagnosis etc. We could test first but I bet you it would be helpful

**Comment by yardencsGitHub** [comment]
That would be awesome!

**Comment by NickleDave** [comment]
these are on the to-do list for `vak`, removing from the paper repository
https://github.com/NickleDave/vak/issues/5
https://github.com/NickleDave/vak/issues/89
