### ISSUE TITLE
change get_seq to from_file in yarden2seq

### ISSUE THREAD

**Issue by karendejong** [yardencsGitHub/tweetynet#25]
Or at least I think that is the solution to the error message I got when trying to run vak, but it may also be a version issue?

**Comment by NickleDave** [comment]
Hi @karendejong I am just about to release a new version of vak (like, within an hour) that should fix this problem.

It's because I didn't pin the version of crowsetta that vak uses, so the most recent version of crowsetta gets installed, that the current version of vak does not use (although a newer version will use it).

I fixed this in the vak source 
https://github.com/NickleDave/vak/issues/67
but I failed to get a new version of vak on PyPI so that it would be fixed when you `pip install vak`.

That's why I'm releasing the new bugfix version today.

Thank you for suggesting a solution though!
You are right that I will need to update the `to_seq` argument when vak switches to using the new version of crowsetta

**Comment by NickleDave** [comment]
Correction: will release some time today ... tests take a while to run, sorry

**Comment by NickleDave** [comment]
Hi @karendejong just letting you know I did release a new version of `vak` that should've fixed this issue.

Instructions on how to install are here:
https://vak.readthedocs.io/en/latest/get_started/installation.html

Please let me know if that does not fix the problem for you

**Comment by karendejong** [comment]
Thanks!

**Comment by NickleDave** [comment]
Sure thing.

If you tell me a little more about what you're trying to do I can give you more specific help.

I'm currently in the middle of a version that will add a walkthrough to the docs with the specific dataset that uses those Annotation.xml files.

**Comment by karendejong** [comment]
Hi, and thanks,
I am trying to run tweetynet on fish sounds together with a colleage. We have figured out how to change the config file and to start running the model with vak, but we are having trouble finding out what the training data should look like. We have a single wav-file of several hours length and a vector with annotations, should we split it up to make spectrograms of a certain length and then create an index file in matlab? Or can we use crowsetta to do this? We would be happy to give feedback on your walk through if you are ready to share a preliminary version.
All the best, Karen

**Comment by karendejong** [comment]
Update: We found the example data in crowsetta, but we cant figure out how to make the annotations so that they will be read by tweetynet. In particular, we would really like to see an example of a training file, such as Bird1_prep_190616_063505.train.vds.json
Because we do not have an xmal file to start with, it may be easier for us to create a train.vds.json directly from our annotation sequence? 
Thanks for any help, Karen

**Comment by NickleDave** [comment]
Fish sounds? Cool, hope we can help.

I have it on my to-do list to write the walkthrough this weekend.

Big picture: yes, I think you will want to split up your .wav file somehow.
Just to make sure: you already have some annotated data, and your goal is to use that to train a model to auto-annotate all the rest, right? And the fish sounds consist of segments with defined onsets and offsets? I.e., however you annotate them, your annotations include a start, stop, and a label for each segment?

If yes, then what you want to do is use `vak` to make one of the `.vds.json` files from your training data. I have no idea how much you need for what you're doing, but for one species of songbird with ~10 syllable types and somewhat variable syntax we can use as little as 1-2 minutes of data and achieve low error rates. You want that 1-2 minutes to contain all the classes you're trying to label (e.g. 5 types of fish sounds and silence in-between them. Or however many sounds you have). Sorry if this is stuff you already know; just want to make sure I'm helping you with what you actually want to do.

If you have a certain type of spectrogram you really like already, you can try training with those as long, as you can get them in .npz or .mat files in a way that `vak` understands. Or you can just let `vak` make the .npz files directly from .wav files.

The details of getting either way (your spects or ours) to work depend on how you're annotating though.  Yes, you are right that you do not want to make one those `Annotation.xml` formats. It sounds like you might have them in a .mat file or something already?
Do you have some program you're using to annotate the data? Like Praat or Audacity?
The point of `crowsetta` is to take the files made by those programs and convert the annotations in the files into the vectors of labeled timebins (i.e. one label for each column of a spectrogram) that `vak` uses to train `TweetyNet` models. Tell me more about the annotations you have now and I can help you figure out how to get `vak` to use `crowsetta` to read them in the right way.

One thing I need to do is add an option for `vak` to use `.csv` files that you can create with `crowsetta` regardless of what format you start with.

And again you might have figured this out already, but basically once we figure out how to get your audio split up and your annotations into a format `vak` can work with, you will run
`$ vak prep config.ini`
from the command line to create the `vds.json` files, and then run
`$ vak train config.ini`
after the file gets made. `vak` adds the path to the `.vds.json` file to the config.ini file for you.

Thank you for your patience and feel free to let me know what other questions you have.
I could Skype or Hangouts or something like that with you all after Wednesday this coming week (work deadline) if that would help.

**Comment by karendejong** [comment]
Hi, thanks a lot for your help, 
it would be great if this works. We are looking for fish sounds in long recordings, and are using only one sound type to start with. We would like the algorithm to run through the recordings and tell us where the onsets and ends (is that what you call offsets?) of the sounds are. I have about six hours of annotated recordings in two files and have used praat to annotate them. I have already written a code in python to upload both the wav-files and the praat-annotation-files, so if I could use the objects I created in python that would be easiest for me. I translated the annotations to a vector of zero's and one's with a total length of the number of samples in the wav file (ones where the sounds are, zeros where there is no sound), my code is here: https://github.com/karendejong/findingcodsounds/blob/master/soundsandtags_simple.py, if you want to have a look. It would be easiest to cut both the sounds and the annotation vectors into smaller parts there, in stead of cutting them separately in Praat, but  if that is not possible, it would be great if you could explain how to use crowsetta for praatfiles. It seems that tweetynet can do much more than just find a single sound type, but I thought if we first focus on getting a simple task to work, we can try more complicated tasks later.
I also have some deadlines next week, but a skypemeeting the week after would be great.
Thanks again, Karen
