### ISSUE TITLE
Conflicts between tweetynet and crowsetta

### ISSUE THREAD

**Issue by NeolithEra** [yardencsGitHub/tweetynet#28]
Hi, users are unable to run **_tweetynet_** due to dependency conflict with _**crowsetta**_ package. As shown in the following full dependency graph of **_tweetynet_**, **_tweetynet_** requires _**crowsetta >=1.0.0**_，while **_vak_** requires **_ crowsetta ==1.1.1_**.

According to pip’s _“first found wins”_ installation strategy, _**crowsetta 2.1.0**_ is the actually installed version. However, _** crowsetta 2.1.0**_ does not satisfy **_==1.1.1_**.

### Dependency tree-----------
```
tweetynet - 0.2.0
| +- crowsetta(install version:2.1.0 version range:>=1.0.0)
| +- vak(install version:0.2.0 version range:*)
| | +- attrs(install version:19.3.0 version range:*)
| | +- crowsetta(install version:1.1.1 version range:==1.1.1)
| | | +- attrs(install version:19.3.0 version range:*)
| | | +- evfuncs(install version:0.2.1 version range:*)
| | | | +- numpy(install version:1.18.0rc1 version range:*)
| | | | +- scipy(install version:1.4.1 version range:>=1.2.0)
| | | +- koumura(install version:0.1.1a1 version range:*)
| | | +- numpy(install version:1.18.0rc1 version range:*)
| | +- dask(install version:2.9.0 version range:*)
| | +- joblib(install version:0.14.1 version range:*)
| | +- matplotlib(install version:3.2.0rc1 version range:*)
| | | +- cycler(install version:0.10.0 version range:>=0.10)
| | | | +- six(install version:1.13.0 version range:*)
| | | +- kiwisolver(install version:1.1.0 version range:>=1.0.1)
| | | | +- setuptools(install version:42.0.2 version range:*)
| | | +- numpy(install version:1.18.0rc1 version range:>=1.11)
| | | +- pyparsing(install version:2.4.5 version range:>=2.0.1)
| | | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| | +- numpy(install version:1.18.0rc1 version range:*)
| | +- scipy(install version:1.4.1 version range:*)
| | +- tensorflow(install version:2.1.0rc1 version range:*)
| | +- tqdm(install version:4.41.0 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependency to be **_crowsetta ==1.1.1_**. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_vak_** to loose the version range of **_crowsetta_**.
3.	Remove your direct dependency _**crowsetta**_, and use **_crowsetta_** transitively introduced by **_vak_**.

@NickleDave Which solution do you prefer, 1, 2 or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by NickleDave** [comment]
Hi @NeolithEra thanks for your help and your interest in the project.

Both `vak` and `tweetynet` are in the middle of a refactor (like, that's what I'm doing right at this moment). 
See https://github.com/NickleDave/vak/tree/switch-dataset-to-generator and https://github.com/yardencsGitHub/tweetynet/tree/make-keras-model
After the refactor, they will use the current version of `crowsetta`. And the only dependency for `tweetynet` will be `tensorflow-keras` -- `crowsetta` will only be a dependency for users to reproduce results from the paper.

The refactor should be complete by the end of next week at the latest.
I really appreciate your offering to submit a PR but this will be resolved after merging the branches above.
