### ISSUE TITLE
run make_error_curve_with_and_without_output_transforms.py on canary data

### ISSUE THREAD

**Issue by NickleDave** [yardencsGitHub/tweetynet#86]
and add results.csv to results/canaries/learncurve

**Comment by NickleDave** [comment]
this script:
https://github.com/yardencsGitHub/tweetynet/blob/master/src/scripts/make_error_curve_with_and_without_output_transforms.py

**Comment by yardencsGitHub** [comment]
Should have been closed by PR.
But I deleted and recreated the PR by accident
